name: Publish to GitHub

on:
  workflow_dispatch:
  push:
    branches: [ test-vadim ]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check version
      run: .github/scripts/check-nuget-version.sh src/Vim.Math3D.csproj
      shell: bash
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test

    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Pack NuGet package
      run: dotnet pack --no-build --include-symbols -p:SymbolPackageFormat=snupkg -c Release src/Vim.Math3D.csproj -o .

    - name: Push NuGet package
      run: dotnet nuget push *.nupkg -s https://nuget.pkg.github.com/vimaec/index.json -k ${{secrets.GITHUB_TOKEN}}
    - name: Tag commit
      run: .github/scripts/tag-commit.sh src/Vim.Math3D.csproj
