name: Publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
# Check version

    - name: Install additional tools
      run: sudo apt install nuget
    - name: Check version
      run: .github/scripts/check-nuget-version.sh src/Vim.Math3D.csproj Vim.Math3D
      shell: bash

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build

    - name: Pack NuGet package
      run: dotnet pack --no-build --include-symbols -p:SymbolPackageFormat=snupkg -c Release src/Vim.Math3D.csproj -o .
    - name: Push NuGet package
      #run: dotnet nuget push Vim.Math3D*.nupkg -s https://nuget.pkg.github.com/vimaec/index.json -k ${{secrets.GITHUB_TOKEN}}
      run: dotnet nuget push Vim.Math3D*.nupkg -k ${{secrets.NUGET_KEY}}
    - name: Tag commit
      run: .github/scripts/tag-commit.sh src/Vim.Math3D.csproj
